dist: xenial
language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python3 src/generate_urlhaus_list.py
  - python3 src/generate_bambenek_list.py

after_success:
  - git config --global push.default simple
  - git config user.name "tjnel"
  - git remote add origin https://${GITHUB_TOKEN}@github.com/tjnel/LC_OSINT_Feeds.git
  - git add .
  - git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"
  - git push origin master --quiet