dist: xenial
language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python3 src/generate_urlhaus_list.py
  - python3 src/generate_bambenek_list.py

after_success:
  - rm -rf .git/
  - git init
  - git config --global push.default simple
  - git remote add origin https://${GITHUB_TOKEN}@github.com/tjnel/LC_OSINT_Feeds.git
  - git push origin master --quiet
  - make github